/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface EikjsonSchema {
  /**
   * The URL address of the Eik server where packages are published to.
   */
  server: string;
  /**
   * The name of the Eik package. Follows the same rules as for NPM package names. Must be parseable by validate-npm-package-name package, which is bundled with npm as a dependency.
   */
  name: string;
  /**
   * The version of the Eik package. Follows the same rules as for NPM package versions. Must be parseable by node-semver, which is bundled with npm as a dependency.
   */
  version: string;
  /**
   * The type of the Eik package. Must be one of 'package', 'npm' or 'map'. Setting this value changes the URL publish namespace between '/pkg' (default), '/npm' and '/map', use 'npm' when publishing NPM packages. Use 'map' when publishing import maps.
   */
  type?: "package" | "npm" | "map";
  /**
   * File mapping definition for the package. Keys represent files or paths to be created on the Eik Server. Values represent paths to local files to be published.
   */
  files:
    | {
        [k: string]: string;
      }
    | string;
  /**
   * Import map files given by URL(s) to be used during package bundling. Specified as a URL or array of URLs. URLs are locations of import map files that follow the W3C import map spec.
   */
  "import-map"?: string | string[];
  /**
   * Location of local Eik build directory (defaults to .eik). Used by Eik client.
   */
  out?: string;
}
